### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by barryvdh** [goszowski/laravel-vendor-minify#1]
Hey,

Please just don't copy my package (https://github.com/barryvdh/laravel-vendor-cleanup) and rename it, without providing any attribution.

**Comment by goszowski** [comment]
Hey.
For the first, I not just copied, but somewhat rewrote the Console Command and created a new ServiceProvider.
Secondly, your package has a MIT license.
On the third - you are in the first place among the contributors.
What do you want me to add? What information and where?
![image](https://user-images.githubusercontent.com/10208931/57175531-cfdaa880-6e55-11e9-9c9b-1789fcacdbb9.png)

**Comment by barryvdh** [comment]
Just a reference that the things you used, were created/based on the original package. Eg a reference in the VendorCleanupCommand, which is basically a copy (see https://github.com/goszowski/laravel-vendor-minify/commit/1261b7a6048cc3b9965480af542e146fff651362) would suffice. But it's MIT so no problem of using it.
